learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines URL patterns for users."""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.TextInput(attrs={'placeholder': 'Type here...'})}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'placeholder': 'Start typing/writing here...', 'cols': 100,   'rows': 10})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Check for valid topic owner.
def check_topic_owner(owner, user):
    if owner != user:
        raise Http404
    else:
        pass

# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure the topic belongs to the current user.
    check_topic_owner(topic.owner, request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particiular topic."""
    topic = Topic.objects.get(id=topic_id)
    # Make sure the topic belongs to the current user.
    check_topic_owner(topic.owner, request.user)
    
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # Display a blank or invalid form.
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # Make sure the topic belongs to the current user.
    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')
    
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
	<meta name="theme-color" content="#ffd600" />
	<meta name="msapplication-navbutton-color" content="#ffd600" />

	<title>{% block title %}{% endblock title %}</title>
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.svg' %}"/>

	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}

	<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
	{% block stylesheet %}{% endblock stylesheet %}

  <script>
    window.addEventListener('load', () => {
      document.querySelector(".preloader").style.cssText = `opacity: 0; visibility: hidden;`;
    })
  </script>
</head>

<body>

	<div class="preloader">
		<div class="loader">
			<div class="loader-inner">
				<img src="{% static 'img/favicon.svg' %}"/>
			</div>
		</div>
	</div>

	<header>
		<nav class="navbar navbar-expand-sm container">
			<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
				{% block navbarlogo %}{% endblock navbarlogo %}
			</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
				<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" viewBox="0 0 30 30">
					<path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2.5" d="M4 7h22M4 15h22M4 23h22"/>
				</svg>
			</button>

			<div class="collapse navbar-collapse" id="navbarCollapse">
				<ul class="navbar-nav ml-auto">

					{% if user.is_authenticated %}
					<li class="nav-item">
						<span class="navbar-text">
							Hello, {{ user.username }}.
							<svg width="208" height="11" viewBox="0 0 208 11" fill="none" xmlns="http://www.w3.org/2000/svg">
								<path d="M8.90002 10.1C72.2 10.6 135.6 10.7 198.9 10.5C200.8 10.5 200.8 7.49998 198.9 7.49998C135.6 7.79998 72.2 7.69998 8.90002 7.09998C6.90002 7.09998 6.90002 10.1 8.90002 10.1Z" fill="currentColor"/>
								<path d="M1.90002 3.79999C69.9 3.79999 137.9 4.09999 205.9 4.89999C207.8 4.89999 207.8 1.89999 205.9 1.89999C137.9 1.19999 69.9 0.799988 1.90002 0.799988C-0.0999756 0.799988 -0.0999756 3.79999 1.90002 3.79999Z" fill="currentColor"/>
							</svg>
						</span>
					</li>
					{% block navbarnewbtn %}{% endblock navbarnewbtn %}
					<li class="nav-item">
						<a class="nav-link logout-btn" href="{% url 'users:logout' %}">
							Log Out
						</a>
					</li>

					{% else %}
					<li class="nav-item">
						{% block navbarbtntext %}{% endblock navbarbtntext %}
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>
	</header>

	<main role="main">
		<div class="container p-0">
			{% block page_content %}{% endblock page_content %}
		</div>
		{% comment %}
		<div class="container p-0">
			{% block body_content %}{% endblock body_content %}
		</div>
		{% endcomment %}
	</main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}Edit Entry | Topic: {{ topic }}{% endblock title %}

{% block stylesheet %}
	<link rel="stylesheet" href="{% static 'css/edit_entry.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
	<img
		src="{% static 'img/logo-light.svg' %}"
		class="d-inline-block align-top"
		alt="Logo"
	/>
{% endblock navbarlogo %}

{% block navbarnewbtn %}
	<li class="nav-item">
		<a class="nav-link new-btn" href="{% url 'learning_logs:topics' %}">
			All Topics
		</a>
	</li>
	<li class="nav-item">
    <a class="nav-link new-btn" href="{% url 'learning_logs:topic' topic.id %}">
      Entries
    </a>
  </li>
{% endblock navbarnewbtn %}

{% block page_content %}

	<div class="topics_banner">
		<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
			
			<div class="topics_header">
				<h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
				<button name="submit">
					<span>Save Changes</span>
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor">
						<path d="M433.1 129.1l-83.9-83.9C342.3 38.32 327.1 32 316.1 32H64C28.65 32 0 60.65 0 96v320c0 35.35 28.65 64 64 64h320c35.35 0 64-28.65 64-64V163.9C448 152.9 441.7 137.7 433.1 129.1zM224 416c-35.34 0-64-28.66-64-64s28.66-64 64-64s64 28.66 64 64S259.3 416 224 416zM320 208C320 216.8 312.8 224 304 224h-224C71.16 224 64 216.8 64 208v-96C64 103.2 71.16 96 80 96h224C312.8 96 320 103.2 320 112V208z"/>
					</svg>
				</button>
			</div>

			<p>Edit your entry for <span>{{ topic }}</span> below:</p>

			{% csrf_token %}
			{{ form.as_p }}

		</form>
	</div>

	<div class="bg-pattern"></div>

{% endblock page_content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}Learning Log{% endblock title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
  <img
    src="{% static 'img/logo-dark.svg' %}"
    class="d-inline-block align-top"
    alt="Logo"
  />
{% endblock navbarlogo %}

{% block navbarbtntext %}
  <a class="nav-link" href="{% url 'users:register' %}">
    Get Started
  </a>
{% endblock navbarbtntext %}

{% block page_content %}
  <div class="row">
    <div class="banner-content col-md-7">

      {% if user.is_authenticated %}
      <h5>Welcome <span>{{ user.username }}</span></h5>
      {% endif %}

      <h1>Track your <span>learning</span></h1>

      <p>
        Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.
      </p>

      {% if user.is_authenticated %}
        <a href="{% url 'learning_logs:topics' %}" class="btn" role="button">
          Go to Topics
        </a>
      {% else %}
        <a href="{% url 'users:login' %}" class="btn" role="button">
          Log In
        </a>
        <p class="link-text">
          Are you new here?
          <a href="{% url 'users:register' %}" class="link" role="button">
            Register Now!
            <svg width="208" height="11" viewBox="0 0 208 11" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M8.90002 10.1C72.2 10.6 135.6 10.7 198.9 10.5C200.8 10.5 200.8 7.49998 198.9 7.49998C135.6 7.79998 72.2 7.69998 8.90002 7.09998C6.90002 7.09998 6.90002 10.1 8.90002 10.1Z" fill="currentColor"></path>
              <path d="M1.90002 3.79999C69.9 3.79999 137.9 4.09999 205.9 4.89999C207.8 4.89999 207.8 1.89999 205.9 1.89999C137.9 1.19999 69.9 0.799988 1.90002 0.799988C-0.0999756 0.799988 -0.0999756 3.79999 1.90002 3.79999Z" fill="currentColor"></path>
            </svg>
          </a>
        </p>
      {% endif %}
    
    </div>

    <div class="banner-image col-md-5">
      <img src="{% static 'img/banner-img.svg' %}" alt="Learning Logs Banner" />
    </div>
  </div>
{% endblock page_content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}New Entry | Topic: {{ topic }}{% endblock title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/new_entry.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
  <img
    src="{% static 'img/logo-light.svg' %}"
    class="d-inline-block align-top"
    alt="Logo"
  />
{% endblock navbarlogo %}

{% block navbarnewbtn %}
  <li class="nav-item">
    <a class="nav-link new-btn" href="{% url 'learning_logs:topics' %}">
      All Topics
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link new-btn" href="{% url 'learning_logs:topic' topic.id %}">
      Entries
    </a>
  </li>
{% endblock navbarnewbtn %}

{% block page_content %}

  <div class="topics_banner">
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">

      <div class="topics_header">
        <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
        <button name="submit">
          <span>Add Entry</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor">
            <path d="M384 32C419.3 32 448 60.65 448 96V416C448 451.3 419.3 480 384 480H64C28.65 480 0 451.3 0 416V96C0 60.65 28.65 32 64 32H384zM339.8 211.8C350.7 200.9 350.7 183.1 339.8 172.2C328.9 161.3 311.1 161.3 300.2 172.2L192 280.4L147.8 236.2C136.9 225.3 119.1 225.3 108.2 236.2C97.27 247.1 97.27 264.9 108.2 275.8L172.2 339.8C183.1 350.7 200.9 350.7 211.8 339.8L339.8 211.8z"/>
          </svg>
        </button>
      </div>

      <p>Add a new entry for <span>{{ topic }}</span> below:</p>

      {% csrf_token %}
      {{ form.as_p }}

    </form>
  </div>

  <div class="bg-pattern"></div>

{% endblock page_content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}New Topic | Learning Log{% endblock title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/new_topic.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
  <img
    src="{% static 'img/logo-light.svg' %}"
    class="d-inline-block align-top"
    alt="Logo"
  />
{% endblock navbarlogo %}

{% block navbarnewbtn %}
  <li class="nav-item">
    <a class="nav-link new-btn" href="{% url 'learning_logs:topics' %}">
      All Topics
    </a>
  </li>
{% endblock navbarnewbtn %}

{% block page_content %}

  <div class="topics_banner">
    <form action="{% url 'learning_logs:new_topic' %}" method="post">

      <div class="topics_header">
        <h2>Add a <span>New Topic</span></h2>
        <button name="submit">
          <span>Add Now</span>
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor">
            <path d="M384 32C419.3 32 448 60.65 448 96V416C448 451.3 419.3 480 384 480H64C28.65 480 0 451.3 0 416V96C0 60.65 28.65 32 64 32H384zM339.8 211.8C350.7 200.9 350.7 183.1 339.8 172.2C328.9 161.3 311.1 161.3 300.2 172.2L192 280.4L147.8 236.2C136.9 225.3 119.1 225.3 108.2 236.2C97.27 247.1 97.27 264.9 108.2 275.8L172.2 339.8C183.1 350.7 200.9 350.7 211.8 339.8L339.8 211.8z"/>
          </svg>
        </button>
      </div>

      <p>Enter your topic name below:</p>

      {% csrf_token %}
      {{ form.as_p }}

    </form>
  </div>

  <div class="bg-pattern"></div>

{% endblock page_content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}{{ topic }} | Topic{% endblock title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/topic.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
  <img
    src="{% static 'img/logo-light.svg' %}"
    class="d-inline-block align-top"
    alt="Logo"
  />
{% endblock navbarlogo %}

{% block navbarnewbtn %}
  <li class="nav-item">
    <a class="nav-link new-btn" href="{% url 'learning_logs:topics' %}">
      All Topics
    </a>
  </li>
{% endblock navbarnewbtn %}

{% block page_content %}

  <div class="topics_banner">
    <div class="topics_header">
      <h2>{{ topic }}</h2>
      <a href="{% url 'learning_logs:new_entry' topic.id %}">
        <span>Add New Entry</span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" fill="currentColor">
          <path d="M0 64C0 28.65 28.65 0 64 0H224V128C224 145.7 238.3 160 256 160H384V198.6C310.1 219.5 256 287.4 256 368C256 427.1 285.1 479.3 329.7 511.3C326.6 511.7 323.3 512 320 512H64C28.65 512 0 483.3 0 448V64zM256 128V0L384 128H256zM288 368C288 288.5 352.5 224 432 224C511.5 224 576 288.5 576 368C576 447.5 511.5 512 432 512C352.5 512 288 447.5 288 368zM448 303.1C448 295.2 440.8 287.1 432 287.1C423.2 287.1 416 295.2 416 303.1V351.1H368C359.2 351.1 352 359.2 352 367.1C352 376.8 359.2 383.1 368 383.1H416V431.1C416 440.8 423.2 447.1 432 447.1C440.8 447.1 448 440.8 448 431.1V383.1H496C504.8 383.1 512 376.8 512 367.1C512 359.2 504.8 351.1 496 351.1H448V303.1z"/>
        </svg>
      </a>
    </div>

    <div class="topics_body">
      {% for entry in entries %}
        <div class="card">
          <div class="card-header">
            <h6>{{ entry.date_added|date:'M d, Y H:i' }} IST</h6>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
              <span>Edit Entry</span>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" fill="currentColor">
                <path d="M373.1 24.97C401.2-3.147 446.8-3.147 474.9 24.97L487 37.09C515.1 65.21 515.1 110.8 487 138.9L289.8 336.2C281.1 344.8 270.4 351.1 258.6 354.5L158.6 383.1C150.2 385.5 141.2 383.1 135 376.1C128.9 370.8 126.5 361.8 128.9 353.4L157.5 253.4C160.9 241.6 167.2 230.9 175.8 222.2L373.1 24.97zM440.1 58.91C431.6 49.54 416.4 49.54 407 58.91L377.9 88L424 134.1L453.1 104.1C462.5 95.6 462.5 80.4 453.1 71.03L440.1 58.91zM203.7 266.6L186.9 325.1L245.4 308.3C249.4 307.2 252.9 305.1 255.8 302.2L390.1 168L344 121.9L209.8 256.2C206.9 259.1 204.8 262.6 203.7 266.6zM200 64C213.3 64 224 74.75 224 88C224 101.3 213.3 112 200 112H88C65.91 112 48 129.9 48 152V424C48 446.1 65.91 464 88 464H360C382.1 464 400 446.1 400 424V312C400 298.7 410.7 288 424 288C437.3 288 448 298.7 448 312V424C448 472.6 408.6 512 360 512H88C39.4 512 0 472.6 0 424V152C0 103.4 39.4 64 88 64H200z"/>
              </svg>
            </a>
          </div>
          <div class="card-body">
            {{ entry.text|linebreaks }}
          </div>
        </div>
      {% empty %}
        <img src="{% static 'img/empty-folder.svg' %}" class="d-block align-top" alt="Empty"/>
        <span class="empty">There are no entries for this topic yet.</span>
      {% endfor %}
    </div>
  </div>

  <div class="bg-pattern"></div>

{% endblock page_content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% load static %}

{% block title %}Topics | Learning Log{% endblock title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/topics.css' %}" />
{% endblock stylesheet %}

{% block navbarlogo %}
  <img
    src="{% static 'img/logo-light.svg' %}"
    class="d-inline-block align-top"
    alt="Logo"
  />
{% endblock navbarlogo %}

{% block page_content %}

  <div class="topics_banner">
    <div class="topics_header">
      <h2>All <span>Topics</span></h2>
      <a href="{% url 'learning_logs:new_topic' %}">
        <span>Add a New Topic</span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" fill="currentColor">
          <path d="M384 32C419.3 32 448 60.65 448 96V416C448 451.3 419.3 480 384 480H64C28.65 480 0 451.3 0 416V96C0 60.65 28.65 32 64 32H384zM224 368C237.3 368 248 357.3 248 344V280H312C325.3 280 336 269.3 336 256C336 242.7 325.3 232 312 232H248V168C248 154.7 237.3 144 224 144C210.7 144 200 154.7 200 168V232H136C122.7 232 112 242.7 112 256C112 269.3 122.7 280 136 280H200V344C200 357.3 210.7 368 224 368z"/>
        </svg>
      </a>
    </div>

    <ul class="topics_body">
      {% for topic in topics %}
        <li>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
      {% empty %}
        <li>
          <img src="{% static 'img/empty-folder.svg' %}" class="d-block align-top" alt="Empty"/>
          <span class="empty">No topics have been added yet.</span>
        </li>
      {% endfor %}
    </ul>
  </div>

  <div class="bg-pattern"></div>

{% endblock page_content %}